// flow-typed signature: 3b7abe4244719cef712ab015fb6e5af9
// flow-typed version: <<STUB>>/babel-preset-fbjs_v^3.2.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-fbjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-fbjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-fbjs/configure' {
  declare module.exports: any;
}

declare module 'babel-preset-fbjs/plugins/auto-importer' {
  declare module.exports: any;
}

declare module 'babel-preset-fbjs/plugins/dev-declaration' {
  declare module.exports: any;
}

declare module 'babel-preset-fbjs/plugins/dev-expression' {
  declare module.exports: any;
}

declare module 'babel-preset-fbjs/plugins/inline-requires' {
  declare module.exports: any;
}

declare module 'babel-preset-fbjs/plugins/object-assign' {
  declare module.exports: any;
}

declare module 'babel-preset-fbjs/plugins/rewrite-modules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-fbjs/configure.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/configure'>;
}
declare module 'babel-preset-fbjs/index' {
  declare module.exports: $Exports<'babel-preset-fbjs'>;
}
declare module 'babel-preset-fbjs/index.js' {
  declare module.exports: $Exports<'babel-preset-fbjs'>;
}
declare module 'babel-preset-fbjs/plugins/auto-importer.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/plugins/auto-importer'>;
}
declare module 'babel-preset-fbjs/plugins/dev-declaration.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/plugins/dev-declaration'>;
}
declare module 'babel-preset-fbjs/plugins/dev-expression.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/plugins/dev-expression'>;
}
declare module 'babel-preset-fbjs/plugins/inline-requires.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/plugins/inline-requires'>;
}
declare module 'babel-preset-fbjs/plugins/object-assign.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/plugins/object-assign'>;
}
declare module 'babel-preset-fbjs/plugins/rewrite-modules.js' {
  declare module.exports: $Exports<'babel-preset-fbjs/plugins/rewrite-modules'>;
}
